lib/ibm_watson/iam_token_manager.rb, lib/ibm_watson/websocket/speech_to_text_websocket_listener.rb, rakefile, test/integration/test_assistant_v1.rb, test/integration/test_discovery_v1.rb, test/integration/test_iam_assistant_v1.rb, test/integration/test_speech_to_text_v1.rb, test/integration/test_text_to_speech_v1.rb, test/unit/test_speech_to_text_v1.rb
* Adjust tests to allow for faster testing
* Allow multiple travis jobs to run concurrently
* Increase code coverage to 100%
=> Speed up tests

README.md, examples/assistant_v1.rb, examples/discovery_v1.rb, examples/language_translator_v3.rb, examples/natural_language_classifier_v1.rb, examples/natural_language_understanding_v1.rb, examples/personality_insights_v3.rb, examples/speech_to_text_v1.rb, examples/text_to_speech_v1.rb, examples/tone_analyzer_v3.rb, examples/visual_recognition_v3.rb, lib/ibm_watson/assistant_v1.rb, lib/ibm_watson/discovery_v1.rb, lib/ibm_watson/iam_token_manager.rb, lib/ibm_watson/language_translator_v3.rb, lib/ibm_watson/natural_language_classifier_v1.rb, lib/ibm_watson/natural_language_understanding_v1.rb, lib/ibm_watson/personality_insights_v3.rb, lib/ibm_watson/speech_to_text_v1.rb, lib/ibm_watson/text_to_speech_v1.rb, lib/ibm_watson/tone_analyzer_v3.rb, lib/ibm_watson/visual_recognition_v3.rb, lib/ibm_watson/watson_service.rb, test/integration/test_iam_assistant_v1.rb, test/integration/test_visual_recognition_v3.rb, test/unit/test_iam_token_manager.rb, test/unit/test_language_translator_v3.rb
* Change `iam_api_key` to `iam_apikey` to conform with other sdks.
=> feat(IAM): Change iam_api_key to iam_apikey

README.md, examples/speech_to_text_v1.rb, lib/ibm_watson/assistant_v1.rb, lib/ibm_watson/discovery_v1.rb, lib/ibm_watson/speech_to_text_v1.rb, test/integration/test_speech_to_text_v1.rb, test/unit/test_assistant_v1.rb, test/unit/test_discovery_v1.rb
* Rename `recognize_with_websocket` to `recognize_using_websocket`
* Deprecate `recognize_with_websocket`
* Regenerate services with the newest definitions and changes
=> Rename websocket method and Regenerate assistant and discovery

test/unit/test_personality_insights_v3.rb
* Fix a unit test for Personality Insights
=> test(Personality Insights): Fix unit test for personality insights

test/appveyor_status.rb
* Ensures that on any commit in `Master`, it makes sure that it checks the corresponding AppVeyor status for the same commit.
=> Modify appveyor checker to check for specific commits

README.md, lib/ibm_watson/discovery_v1.rb, lib/ibm_watson/natural_language_classifier_v1.rb, lib/ibm_watson/speech_to_text_v1.rb, lib/ibm_watson/visual_recognition_v3.rb, test/unit/test_discovery_v1.rb
Thjis PR adds codegen updates using the following commits:
Codegen: 2590ceea86dc97127f9afa67c79a3c321dd68e5c
API definition: 053ee5d76d6bdf82c0cb146a98e459dba2e5b0cd
=> Codegen updates

examples/assistant_v2.rb, lib/ibm_watson.rb, lib/ibm_watson/assistant_v2.rb, lib/ibm_watson/speech_to_text_v1.rb, test/integration/test_assistant_v2.rb, test/unit/test_assistant_v2.rb
This PR is using the following commits:
- Codegen: `4e7a739d8a08e2e18149521400cc26e0ff378280`
- API definition: `8e785da94f0c8d62ade5f8c54c1b73447b9aa321`
=> Regular SDK Release 

lib/ibm_watson/discovery_v1.rb, lib/ibm_watson/personality_insights_v3.rb, lib/ibm_watson/speech_to_text_v1.rb, lib/ibm_watson/text_to_speech_v1.rb, lib/ibm_watson/tone_analyzer_v3.rb, lib/ibm_watson/visual_recognition_v3.rb, lib/ibm_watson/watson_service.rb, test/integration/test_discovery_v1.rb, test/unit/test_discovery_v1.rb
- Regenerate using the selected commits
- Update Tests
=> Sdk release 9

lib/ibm_watson/discovery_v1.rb, lib/ibm_watson/natural_language_understanding_v1.rb, lib/ibm_watson/speech_to_text_v1.rb, test/unit/test_discovery_v1.rb
This PR contains changes for regulare SDK release 10 using the following commits:
`Codegen: 17986b7921b9440e72bfb68d3febeb0cda12b7bd`
`API definition: 69548d73e9f9b65a549772bdc949087959f9a35e`
=> Release 10

.travis.yml, README.md, test/integration/test_speech_to_text_v1.rb
Changes to Travis files because Travis was having issues because of https://bundler.io/blog/2019/01/04/an-update-on-the-bundler-2-release.html.
=> remove assistantv2 beta line from readme

appveyor.yml, ibm_watson.gemspec, lib/ibm_watson.rb, lib/ibm_watson/assistant_v1.rb, lib/ibm_watson/assistant_v2.rb, lib/ibm_watson/common.rb, lib/ibm_watson/compare_comply_v1.rb, lib/ibm_watson/discovery_v1.rb, lib/ibm_watson/language_translator_v3.rb, lib/ibm_watson/natural_language_classifier_v1.rb, lib/ibm_watson/natural_language_understanding_v1.rb, lib/ibm_watson/personality_insights_v3.rb, lib/ibm_watson/speech_to_text_v1.rb, lib/ibm_watson/text_to_speech_v1.rb, lib/ibm_watson/tone_analyzer_v3.rb, lib/ibm_watson/visual_recognition_v3.rb, lib/ibm_watson/watson_service.rb, test/integration/test_speech_to_text_v1.rb, test/unit/test_configure_http_client.rb
=> feat(common): add common class to add default headers

README.md, ibm_watson.gemspec, lib/ibm_watson.rb, lib/ibm_watson/assistant_v1.rb, lib/ibm_watson/assistant_v2.rb, lib/ibm_watson/compare_comply_v1.rb, lib/ibm_watson/discovery_v1.rb, lib/ibm_watson/language_translator_v3.rb, lib/ibm_watson/natural_language_classifier_v1.rb, lib/ibm_watson/natural_language_understanding_v1.rb, lib/ibm_watson/personality_insights_v3.rb, lib/ibm_watson/speech_to_text_v1.rb, lib/ibm_watson/text_to_speech_v1.rb, lib/ibm_watson/tone_analyzer_v3.rb, lib/ibm_watson/visual_recognition_v3.rb, test/unit/test_language_translator_v3.rb
This PR updates core SDK package and add supports for ICP4D.
=> feat(ICP4D): add support for ICP4D

ibm_watson.gemspec, lib/ibm_watson/assistant_v1.rb, lib/ibm_watson/assistant_v2.rb, lib/ibm_watson/compare_comply_v1.rb, lib/ibm_watson/discovery_v1.rb, lib/ibm_watson/language_translator_v3.rb, lib/ibm_watson/natural_language_classifier_v1.rb, lib/ibm_watson/natural_language_understanding_v1.rb, lib/ibm_watson/personality_insights_v3.rb, lib/ibm_watson/speech_to_text_v1.rb, lib/ibm_watson/text_to_speech_v1.rb, lib/ibm_watson/tone_analyzer_v3.rb, lib/ibm_watson/visual_recognition_v3.rb, test/unit/test_watson_service.rb
=> fix(auth): expose display name to parent class to get credentials from file

docker/Dockerfile, docker/README.md
Added dockerfile to ruby-sdk to create an image with the sdk installed that can be used for testing issues.
=> Ruby SDK Dockerfile

lib/ibm_watson/assistant_v1.rb, lib/ibm_watson/assistant_v2.rb, lib/ibm_watson/natural_language_classifier_v1.rb, lib/ibm_watson/personality_insights_v3.rb, lib/ibm_watson/speech_to_text_v1.rb, lib/ibm_watson/text_to_speech_v1.rb, lib/ibm_watson/tone_analyzer_v3.rb, lib/ibm_watson/visual_recognition_v3.rb, lib/ibm_watson/visual_recognition_v4.rb, test/unit/test_visual_recognition_v4.rb
This PR adds the newest generated code using API definition tag sdk-2020-02-10 and generator tag 2.2.4.
=> Release 2 2020

examples/language_translator_v3.rb
test: add document translation examples
=> test: add document translation examples

lib/ibm_watson/speech_to_text_v1.rb, test/integration/test_speech_to_text_v1.rb
fix: correct websocket function
=> fix: correct websocket function

lib/ibm_watson/assistant_v2.rb, lib/ibm_watson/discovery_v2.rb, lib/ibm_watson/text_to_speech_v1.rb, lib/ibm_watson/visual_recognition_v4.rb, test/integration/test_assistant_v2.rb, test/integration/test_visual_recognition_v4.rb, test/unit/test_assistant_v2.rb, test/unit/test_visual_recognition_v4.rb
feat: New features in VR4 and assistant2
=> feat: New features in VR4 and assistant2

.releaserc, .travis.yml
chore: changes to try and fix versioning
=> chore: changes to try and fix versioning

.github/workflows/deploy.yml
try to fix the failure on deploy, that is really not a failure.
=> ci: try continue-on-error

lib/ibm_watson/text_to_speech_v1.rb
=> fix: remove filename

lib/ibm_watson/assistant_v1.rb, lib/ibm_watson/assistant_v2.rb, lib/ibm_watson/compare_comply_v1.rb, lib/ibm_watson/discovery_v1.rb, lib/ibm_watson/discovery_v2.rb, lib/ibm_watson/language_translator_v3.rb, lib/ibm_watson/natural_language_classifier_v1.rb, lib/ibm_watson/natural_language_understanding_v1.rb, lib/ibm_watson/personality_insights_v3.rb, lib/ibm_watson/speech_to_text_v1.rb, lib/ibm_watson/text_to_speech_v1.rb, lib/ibm_watson/tone_analyzer_v3.rb, lib/ibm_watson/visual_recognition_v3.rb, lib/ibm_watson/visual_recognition_v4.rb, rakefile
=> fix: new release

.github/workflows/integration-test.yml
=> ci: Gha d2

.github/workflows/deploy.yml, .github/workflows/integration-test.yml
change node to 14, few other minor fixes
=> ci: Gha 9926
